services:
  - type: web
    name: bag-pack
    env: node
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build && cd ../server && npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string
      - key: PORT
        value: 10000
